version: '2.1'
orbs:
  node: circleci/node@5.0.0
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    executor:
      name: node/default
      tag: '16.13.2'
    steps:
      - checkout
      - node/install-packages:
        node-version: '16.13.2'
      - run:
          command: npm run test
  deploy-job:
    executor: heroku/default
    parameters:
      env:
        type: string
        default: staging
    steps:
      - checkout
      - heroku/deploy-via-git:
          app-name: blockassist-harmony-<< parameters.env >>
          force: true

workflows:
  test_app:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - develop
                - main
  build-staging:
    jobs:
      - test:
          name: test-staging-job
          filters:
            branches:
              only: develop
      - deploy-job:
          name: deploy-staging-job
          env: staging
          requires:
            - test-staging-job
  build-production:
    jobs:
      - test:
          name: test-production-job
          filters:
            branches:
              only: main
      - deploy-job:
          name: deploy-production-job
          env: production
          requires:
            - test-production-job
